CREATE TABLE IF NOT EXISTS users(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  username VARCHAR(255),
  password VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS roles(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_roles(
  user_id INT NOT NULL ,
  role_id INT NOT NULL ,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (role_id) REFERENCES roles(id),
  UNIQUE (user_id, role_id)
);